//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Drater.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Eleve
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Eleve()
        {
            this.Retard = new HashSet<Retard>();
            this.Vote_Eleve = new HashSet<Vote_Eleve>();
        }
    
        public long id { get; set; }
        public string pseudo { get; set; }
        public string mail { get; set; }
        public string mdp { get; set; }
        public long idClasse { get; set; }
        public string photo_profile { get; set; }
    
        public virtual Classe Classe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Retard> Retard { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vote_Eleve> Vote_Eleve { get; set; }
    }
}
