//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Drater.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Retard
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Retard()
        {
            this.Vote_Eleve = new HashSet<Vote_Eleve>();
        }
    
        public long id { get; set; }
        public string titre { get; set; }
        public string description { get; set; }
        public long idEleve { get; set; }
        public string pj { get; set; }
    
        public virtual Eleve Eleve { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vote_Eleve> Vote_Eleve { get; set; }

        public int getNbVotes()
        {
            int trendVote = 0;
            foreach (var item in Vote_Eleve)
            {
                if (item.valeur)
                {
                    trendVote++;
                }
                else
                {
                    trendVote--;
                }
            }

            return trendVote;
        }
    }
}
