//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Drater.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Retards_Tags
    {
        public long Id_Retard { get; set; }
        public long Id_Tags { get; set; }
        public long Id { get; set; }
    
        public virtual Retard Retard { get; set; }
        public virtual Tags Tags { get; set; }
    }
}
