//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Drater.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vote_Eleve
    {
        public long id { get; set; }
        public long idEleve { get; set; }
        public long idRetard { get; set; }
        public System.DateTime dateVote { get; set; }
        public bool valeur { get; set; }
    
        public virtual Eleve Eleve { get; set; }
        public virtual Retard Retard { get; set; }
    }
}
